Feat web api with session
shengwei0515/studygroup-backend pull request #3
Opened 2022-09-13 03:46 UTC by Ying-Syuam-Wang

2022-09-13 16:07 UTC, shengwei0515 requested changes
留了小建議
再麻煩看看

2022-09-13 16:07 UTC, shengwei0515 commented on db/postgres/postgres.go
> +		err = Init()
我猜這邊之後都會希望 call 有 retry 的
要不要把 Init() 變成 private function
init() 就好

2022-09-13 16:07 UTC, shengwei0515 commented on db/postgres/postgres.go
> +			break
應該可以直接 return 就好
這樣下面也不用再判斷 if err != nil
也可以藉機 Reduce Nested

2022-09-14 04:24 UTC, Ying-Syuam-Wang commented on db/postgres/postgres.go
> +		err = Init()
Thanks and done!

2022-09-14 04:24 UTC, Ying-Syuam-Wang commented on db/postgres/postgres.go
> +			break
Thanks and done!

2022-09-14 04:30 UTC, merged